/**
 * Canonical portal legal text, copied verbatim from the live legacy portal
 * (src/app/portal/[token]/page.tsx). Duplicated rather than imported because
 * the legacy page keeps these as private consts and must stay untouched
 * until v2 is verified and cut over. If the legal language changes, update
 * BOTH files until the legacy portal is retired.
 */

export const RENTAL_TERMS = [
  { n: 1, title: 'Indemnity', text: `Lessee/Renter ("You") agree to defend, indemnify, and hold SirReel Production Vehicles, Inc. dba SirReel Studio Rentals our agents, employees, assignees, suppliers, sub-lessors and sub-renters ("Us" or "We") harmless from any and all claims, damages, costs, and expenses arising from the Equipment, except as the result of our sole negligence or willful act, from the time the Equipment leaves our place of business until returned to us during normal business hours and we sign a written receipt for it.` },
  { n: 2, title: 'Loss of or Damage to Equipment', text: `You are responsible for loss, damage or destruction of the Equipment, including losses while in transit, loading and unloading, at any locations, in storage and on your premises, except damage caused by our sole negligence or willful misconduct.` },
  { n: 3, title: 'Protection of Others', text: `You will take reasonable precautions in regard to the use of the Equipment to protect all persons and property from injury or damage. The Equipment shall be used only by your employees or agents qualified to use the Equipment.` },
  { n: 4, title: 'Equipment in Working Order', text: `We have tested the Equipment in accordance with reasonable industry standards and found it to be in working order immediately prior to the inception of this Agreement. You acknowledge that the Equipment is rented/leased without warranty or guarantee, except as required by law or otherwise agreed upon by the parties.` },
  { n: 5, title: 'Property Insurance', text: `You shall maintain all risk perils property insurance covering the Equipment including coverage for theft, mysterious disappearance, and loss of use. The Property Insurance shall name us as additional insured and loss payee, shall be primary and Non-Contributory, with minimum coverage of $1,000,000.` },
  { n: 6, title: 'Workers Compensation & Employers Liability Insurance', text: `You shall maintain worker's compensation/employer's liability insurance during the Equipment rental with minimum limits of $1,000,000, including coverage for volunteers, interns, or independent contractors working on your behalf.` },
  { n: 7, title: 'Liability Insurance', text: `You shall maintain commercial general liability insurance naming us as additional insured, providing primary and Non-Contributory coverage with aggregate limits of not less than $2,000,000 and not less than $1,000,000 per occurrence.` },
  { n: 8, title: 'Vehicle Insurance', text: `You shall maintain business motor vehicle liability insurance covering owned, non-owned, hired and rented vehicles. We shall be named as additional insured and loss payee. The Vehicle Insurance shall provide not less than $1,000,000 in combined single limits and shall be primary and Non-Contributory.` },
  { n: 9, title: 'Insurance Generally', text: `All insurance shall contain a waiver of subrogation rights. Lapse, reduction in coverage or cancellation of the required insurance shall be deemed an immediate and automatic default of this agreement.` },
  { n: 10, title: 'Cancellation of Insurance', text: `You and your insurance company shall provide us with not less than 30 days written notice prior to the effective date of any cancellation or material change to any insurance maintained pursuant to this Agreement.` },
  { n: 11, title: 'Certificates of Insurance', text: `Before obtaining possession of the Equipment you shall provide to us Certificates of Insurance confirming all required coverages. All certificates shall be signed by an authorized agent or representative of the insurance carrier.` },
  { n: 12, title: 'Drivers', text: `All drivers who drive our Vehicles shall be duly licensed, trained and qualified. You must supply and employ any driver who drives our Vehicles. That driver shall be deemed your employee or covered independent contracted driver for all purposes and shall be covered as an additional insured on all your applicable insurance policies.` },
  { n: 13, title: 'Compliance With Law and Regulations', text: `You agree to comply with the laws of all states in which the Equipment is transported or used, as well as all federal and local laws, regulations, and ordinances pertaining to the transportation and use of the Equipment.` },
  { n: 14, title: 'Valuation of Loss', text: `You shall be responsible to us for the replacement cost value or repair cost of the Equipment, whichever is less. If theft is suspected, you shall file a police report. WE WILL NOT BE LIABLE FOR ANY CONSEQUENTIAL, SPECIAL OR INCIDENTAL DAMAGES.` },
  { n: 15, title: 'Subrogation', text: `You hereby agree that we shall be allowed to subrogate for any recovery rights you may have for damage to the Equipment.` },
  { n: 16, title: 'Bailment', text: `This agreement constitutes a bailment of the Equipment and is not a sale. You will not acquire any right, title, or interest in the Equipment except the right to possession and use as provided in this Agreement.` },
  { n: 17, title: 'Condition of Equipment', text: `You assume all obligation and liability for the Equipment's use, condition and storage during the Agreement. You will maintain the Equipment in good mechanical condition at your own expense.` },
  { n: 18, title: 'Identity', text: `We have the right to place on each piece of Equipment the inscription: "Property of SirReel." You will not remove, obscure, or deface this inscription.` },
  { n: 19, title: 'Expenses', text: `You will be responsible for all expenses including fuel, lubricants, and all other charges in connection with the operation of the Equipment.` },
  { n: 20, title: 'Accident Reports', text: `If any Equipment is damaged, lost, stolen, or destroyed, or if any person is injured, you will promptly notify us and file all necessary accident reports required by law and applicable insurers.` },
  { n: 21, title: 'Default', text: `If you fail to pay any fees or otherwise materially breach this Agreement, such failure shall constitute a Default. Upon Default, we shall have the right to terminate this Agreement and cease performance hereunder.` },
  { n: 22, title: 'Return', text: `Upon expiration of this Agreement, you will return all Equipment to us with all accessories, free from damage and in the same condition as when received.` },
  { n: 23, title: 'Additional Equipment', text: `Additional Equipment may be added by written amendment signed by both parties. This Agreement may not otherwise be amended except in writing signed by both parties.` },
  { n: 24, title: 'Entire Agreement', text: `This Agreement constitutes the entire agreement between the parties. No other representations or warranties shall be binding unless set forth in writing and signed by both parties.` },
  { n: 25, title: 'Applicable Law', text: `This Agreement shall be governed by the laws of the State of California.` },
  { n: 26, title: 'Arbitration', text: `Any dispute arising out of this Agreement shall be settled by arbitration in Los Angeles, California under JAMS. The arbitrator's decision shall be final and binding. The prevailing party shall be entitled to reasonable attorneys fees and costs.` },
  { n: 27, title: 'Severability', text: `If any provision of this Agreement is held invalid or unenforceable, the remainder of this Agreement shall remain valid and in full force and effect.` },
  { n: 28, title: 'Facsimile Signature', text: `This Agreement may be executed by facsimile signature and such signature shall be deemed a valid and binding original signature.` },
  { n: 29, title: 'Non-smoking Policy', text: `All vehicles are non-smoking. A $250 per day fee may be charged in addition to repair costs if the smoking policy is not observed.` },
]

export const LCDW_TERMS: { heading: string; text: string }[] = [
  { heading: '1. Nature of this Agreement.', text: `The agreement is between you and SirReel Production Vehicles, Inc. DBA SirReel Studio Rentals (SIRREEL). SirReel rents to You the vehicle identified on the Rental Record ("Vehicle") subject to the Rental Record and these Terms and Conditions. You and Authorized Drivers: (a) are not agents of SirReel; (b) may not transfer the Vehicle or any rights or obligations under this Agreement; or (c) may not service or repair the Vehicle without SirReel's prior express approval. SIRREEL MAKES NO EXPRESS OR IMPLIED WARRANTY OF MERCHANTABILITY OR THAT THE VEHICLE IS FIT FOR ANY PARTICULAR PURPOSE.` },
  { heading: '2. Who may Drive the Vehicle.', text: `Only You, and with Your permission, Your spouse, employer and coworkers incidental to their business with You, and persons listed as Additional Drivers may drive the Vehicle. All Authorized Drivers must be at least 25 years old and have a valid driver's license.` },
  { heading: '3. Vehicle Returns.', text: `You must return the Vehicle in the same condition as when received (except for ordinary wear) to SirReel's location on the day and time specified. In no event may You keep the Vehicle for more than thirty (30) days. Failure to return the Vehicle when due terminates SirReel's permission to use the Vehicle.` },
  { heading: '4. Responsibility for Loss of or Damage to the Vehicle.', text: `Regardless of fault, You are responsible for the loss of or damage to the Vehicle except for ordinary wear. (b) If You purchase the Limited Collision Damage Waiver (LCDW) (which is not insurance) at the beginning of the rental, SirReel will not hold You responsible for the first $1,000 in loss of or damage to the Vehicle (including loss of use, towing, storage, impound, and administrative charges) except: (1) when theft occurs or (2) if the Vehicle is used as prohibited in Paragraph 5.` },
  { heading: '5. Prohibited Uses of the Vehicle.', text: `You and Authorized Drivers may NOT permit the Vehicle to be driven: (a) by anyone under the influence of alcohol or drugs; (b) outside the United States, off road, to tow or push anything without prior written permission; (c) to transport persons for compensation or in any speed test; (d) in connection with conduct that could be charged as a felony; (e) in a willful, wanton, or reckless manner; (f) if obtained by fraudulent statements; (g) to transport hazardous or explosive substances; (h) without using seatbelts; (i) in connection with any illegal conduct.` },
  { heading: '6. Payment of Charges.', text: `You will pay SirReel on demand all amounts incurred including: (a) a refueling charge at $10.00/gallon if You return the Vehicle with less fuel than received; (b) all fines, penalties, and attorney's fees unless due to SirReel's fault; (c) all charges related to loss or damage to the Vehicle; (d) all time and mileage charges as computed on the Rental Record.` },
  { heading: '7. Accidents, Theft, Vandalism and Claim Reporting.', text: `You must immediately report any accident, theft, or vandalism to SirReel and to the police. You must promptly deliver to SirReel any papers relating to such incident. FAILURE TO COOPERATE MAY VOID ANY LIABILITY INSURANCE COVERAGE AND ANY LIMITATION OF YOUR RESPONSIBILITY FOR LOSS OF OR DAMAGE TO THE VEHICLE.` },
  { heading: '8. Personal Property.', text: `SirReel is not responsible for loss or damage to Your personal property left in or about the Vehicle.` },
  { heading: '9. Additional Terms.', text: `Any modification of this Agreement is null and void unless in writing signed by You and SirReel. If any part of this Agreement is held void or unenforceable, the validity of the remaining parts shall not be affected.` },
  { heading: '10. Liability Insurance and Indemnity.', text: `You warrant that you have and will maintain automobile liability insurance with limits equal to or greater than those required by law. In the event of an accident, your insurance shall be primary and Non-Contributory.` },
  { heading: '11. Loss of Use.', text: `In the event of damage or destruction of a vehicle, you will pay for loss of use without regard to fleet utilization, plus an administrative fee, plus towing and storage charges.` },
  { heading: 'LIMITED COLLISION DAMAGE WAIVER:', text: `By accepting LCDW herein, Lessee agrees to pay the sum of $24.00/day/vehicle for a Limited Collision Damage Waiver and also agrees to pay all costs above $1,000 as stated in paragraph 4. In exchange, SirReel waives the claim to the first $1,000 in damages caused to the vehicle by collision with another vehicle or property. This waiver does NOT apply to: Prohibited Uses in Paragraph 5, intentional acts, damage due to insufficient height or clearance, improper loading, abusive handling, towing without written permission, unlicensed or revoked drivers, or theft of the vehicle or components.` },
]

export const LCDW_ELIGIBILITY_NOTE = `** LCDW is ONLY available for fleet rental vehicles such as: Cube Trucks, Cargo Vans, Stake Bed Trucks. Specialty Vehicles such as Motorhomes, Combos, PopVans, VTR/PeopleMover Vans, Golf Carts or any vehicle requiring a commercial driver's license are NOT ELIGIBLE for LCDW.`

export const STUDIO_TERMS: { heading: string; text: string }[] = [
  { heading: '1. Grant.', text: `Licensor grants Producer the non-assignable and non-exclusive right to enter upon the Premises at 8500 Lankershim Blvd, Sun Valley, CA and to use designated Sets for the purpose of making still and motion pictures, commercials, trailers and soundtrack recordings.` },
  { heading: '2. Description.', text: `Producer shall have the right to use the Sets including furniture and fixtures located on or about the Sets.` },
  { heading: '3. Fees, Term and Re-Entry.', text: `Producer may use the Property on the dates specified. Re-entry within 60 days requires 5 days advance written notice and is subject to availability.` },
  { heading: '4. Use, Protection and Restoration.', text: `No smoking, eating or drinking on Sets. No alcohol or illegal drugs. No nudity without written consent. Layout board recommended under all equipment. Producer shall remove all personnel and equipment by end of Term.` },
  { heading: '5. Fees.', text: `Location Fee is due in advance for each day. All additional rentals including Grip, Lighting, and Production Supplies must be contracted through SirReel Studios unless otherwise agreed.` },
  { heading: '6. Utilities.', text: `Producer agrees to pay for any necessary unclogging, pumping or damages to bathrooms caused by misuse.` },
  { heading: '7. Security Deposit.', text: `Producer agrees to pay 100% of the Location Fee as a Security Deposit. The deposit will be deducted from the final bill.` },
  { heading: '8. Time of Payment.', text: `Total Due and Security Deposit must be paid prior to commencement of Term.` },
  { heading: '9. Dark Days.', text: `Any day on which set dressing is left on the Property with no production personnel present. Access during a Dark Day converts it to a Prep, Shoot, or Strike Day.` },
  { heading: '10. Postponement/Cancellation Policy.', text: `All cancellations must be made one week prior to start date. Cancellations inside one week will be billed the full rental rate.` },
  { heading: '12. Products Release.', text: `SirReel has secured rights to use identified products on Standing Sets. Producer may utilize these materials for the Production.` },
  { heading: '13. Production Ownership.', text: `Producer shall be the sole and exclusive owner of all rights in photographs, film, video and sound recordings made pursuant to this Agreement.` },
  { heading: '14. Miscellaneous.', text: `Producer shall not assign this Agreement without Licensor consent. Producer shall indemnify and hold harmless Licensor from any claims arising from Producer's use of the Property. This Agreement is governed by California law with venue in Los Angeles County.` },
]

export const CC_GUARANTEE_TEXT = `This Credit Card Authorization form guarantees the payment of all fees due SirReel Studio Services according to the Rental Agreement. This credit card may be used for Charges and Deposits, Cancellation Fees, Damage to Premises and Equipment, Past Due Balances, Fines, Parking Fees and all fees incurred during a given project/production. I agree that the cardholder is a Personal Guarantor of the charges here described and summarized.`

export const CC_ACK_TEXT = `By submitting this form, I acknowledge that the information above is correct. By signing this form I am authorizing SirReel to charge my card for all fees listed above and to keep my card information on file with the payment processor until the transaction is completed. I also acknowledge and accept the Terms and Conditions stated by SirReel.`

// Stage area keys/labels moved to the single source in
// src/lib/contracts/stageAreas.ts (stageAreaLabel / STAGE_AREAS).
